labels: [Codespaces]
body:
- type: markdown
  attributes: 
   value: Create a discussion about Codespaces here. For all other topics, please check out our [Quick Start Guide.](https://github.com/orgs/community/discussions/141947)

- type: dropdown
  id: topic
  attributes:
    label: Select Topic Area
    description: What would you like to discuss?
    options:
      - "Question"
      - "Product Feedback"
      - "Bug"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  id: text
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
